#!/usr/bin/env python
import subprocess

URGENT_CODE = 33
URGENT_PERCENT_THRESHOLD = 5

def exitCodeFromPercent( percent ):
    if percent < URGENT_PERCENT_THRESHOLD:
        return URGENT_CODE
    else:
        return 0

def iconFromPercent( percent ):
    if percent < 20:
        icon = ""
    elif percent < 40:
        icon = ""
    elif percent < 60:
        icon = ""
    elif percent < 80:
        icon = ""
    elif percent < 98:
        icon = ""
    else:
        icon = ""
    return icon

p = subprocess.Popen(["acpi", "-b"], stdout=subprocess.PIPE)
output, err = p.communicate()
if err is not None:
    print("Error: acpi")
    exit(URGENT_CODE)
else:
    percent = int(output.decode("utf-8").split(" ")[3][:-2])
    exit_code = exitCodeFromPercent(percent)
    icon = iconFromPercent(percent)

    print(icon + " " + str(percent) + "%")

    exit(exit_code)
